apiVersion: apps/v1
kind: Deployment
metadata:
  name: metube
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: metube
  template:
    metadata:
      labels:
        app.kubernetes.io/name: metube
    spec:
      containers:
        - name: metube
          image: alexta69/metube:latest
          ports:
            - name: http
              containerPort: 8081
          env:
            - name: DOWNLOAD_DIR
              value: /downloads
          volumeMounts:
            - name: downloads
              mountPath: /downloads
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 512Mi
      volumes:
        - name: downloads
          persistentVolumeClaim:
            claimName: metube-downloads
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metube-downloads
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: Service
metadata:
  name: metube
  namespace: default
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/name: metube
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: metube
  namespace: default
spec:
  parentRefs:
    - name: main-gateway
      namespace: ingress
  hostnames:
    - metube.budabuda-k8s.duckdns.org
  rules:
    - filters:
        - type: ExternalAuth
          externalAuth:
            protocol: HTTP
            backendRef:
              kind: Service
              name: authelia
              namespace: auth
              port: 80
            http:
              path: /api/authz/ext-authz
              allowedResponseHeaders:
                - Remote-User
                - Remote-Groups
                - Remote-Email
      backendRefs:
        - name: metube
          port: 80
