certificatesResolvers: {}

#hostNetwork: true

ingressRoute:
  dashboard:
    enabled: true

ocsp:
  # -- Enable OCSP stapling support.
  # See https://doc.traefik.io/traefik/reference/install-configuration/tls/ocsp/
  enabled: false

persistence:
  # -- Enable persistence using Persistent Volume Claims
  # ref: http://kubernetes.io/docs/user-guide/persistent-volumes/.
  # It can be used to store TLS certificates along with `certificatesResolvers.<name>.acme.storage`  option
  enabled: true

providers:
  kubernetesCRD:
    enabled: false
    allowCrossNamespace: true
  kubernetesGateway:
    # -- Enable Traefik Gateway provider for Gateway API
    enabled: true
  kubernetesIngressNGINX:
    enabled: true
