schema-version = "1.12.0"


## Install Packages --------------------------------------------------
##  $ flox install gum  <- puts a package in [install] section below
##  $ flox search gum   <- search for a package
##  $ flox show gum     <- show all versions of a package
## -------------------------------------------------------------------
[install]
## atuin group

# atuin alternativy mcfly
atuin.pkg-path = "atuin"
atuin.pkg-group = "atuin"

blesh.pkg-path = "blesh"
blesh.pkg-group = "atuin"

## checkov group

checkov.pkg-path = "checkov"
checkov.pkg-group = "checkov"

## kubectl group

kubectl.pkg-path = "kubectl"
kubectl.version = "1.32.3"
kubectl.pkg-group = "kubectl"

## default pkg-group
ansible.pkg-path = "ansible"
argocd.pkg-path = "argocd"
bat.pkg-path = "bat"
#caskaydia-cove.pkg-path = "nerd-fonts.caskaydia-cove"
claude-code.pkg-path = "claude-code"
crossplane.pkg-path = "crossplane"
delta.pkg-path = "delta"
direnv.pkg-path = "direnv"
fd.pkg-path = "fd"
gemini-cli.pkg-path = "gemini-cli"
git.pkg-path = "git"
git-crypt.pkg-path = "git-crypt"
glow.pkg-path = "glow"
go.pkg-path = "go"
hadolint.pkg-path = "hadolint"
helm-diff.pkg-path = "kubernetes-helmPlugins.helm-diff"
helm-schema.pkg-path = "kubernetes-helmPlugins.helm-schema"
helm-unittest.pkg-path = "kubernetes-helmPlugins.helm-unittest"
helmfile.pkg-path = "helmfile"
cht-sh.pkg-path = "cht-sh"
k9s.pkg-path = "k9s"
krew.pkg-path = "krew"
kubecolor.pkg-path = "kubecolor"
kubectx.pkg-path = "kubectx"
kubernetes-helm.pkg-path = "kubernetes-helm"
kubescape.pkg-path = "kubescape"
kustomize.pkg-path = "kustomize"
mkcert.pkg-path = "mkcert"
mkdocs.pkg-path = "mkdocs"
nelm.pkg-path = "nelm"
openbao.pkg-path = "openbao"
openshift.pkg-path = "openshift"
opentofu.pkg-path = "opentofu"
podman.pkg-path = "podman"
poetry.pkg-path = "poetry"
pyenv.pkg-path = "pyenv"
ripgrep.pkg-path = "ripgrep"
ruby.pkg-path = "ruby"
s3cmd.pkg-path = "s3cmd"
sd.pkg-path = "sd"
starship.pkg-path = "starship"
stern.pkg-path = "stern"
talosctl.pkg-path = "talosctl"
tldr.pkg-path = "tldr"
yq-go.pkg-path = "yq-go"
warp-dir.pkg-path = "pstefka/warp-dir"
goose-cli.pkg-path = "flox/goose-cli"
goose-cli.pkg-group = "goose-cli"
hermes-agent.pkg-path = "flox/hermes-agent"
hermes-agent.pkg-group = "hermes-agent"

## Environment Variables ---------------------------------------------
##  ... available for use in the activated environment
##      as well as [hook], [profile] scripts and [services] below.
## -------------------------------------------------------------------
[vars]
# INTRO_MESSAGE = "It's gettin' Flox in here"
STARSHIP_CONFIG = "$FLOX_ENV_PROJECT/starship.toml"
FLOX_PROMPT_DISABLE = "1"

## Activation Hook ---------------------------------------------------
##  ... run by _bash_ shell when you run 'flox activate'.
## -------------------------------------------------------------------
[hook]
#on-activate = '''
#   # -> Set variables, create files and directories
#   # -> Perform initialization steps, e.g. create a python venv
#   # -> Useful environment variables:
#   #      - FLOX_ENV_PROJECT=/home/user/example
#   #      - FLOX_ENV=/home/user/example/.flox/run
#   #      - FLOX_ENV_CACHE=/home/user/example/.flox/cache
#export PATH="$PWD/.local/bin/:$PATH"
#'''

## Profile script ----------------------------------------------------
## ... sourced by _your shell_ when you run 'flox activate'.
## -------------------------------------------------------------------
[profile]
# common = '''
#   gum style \
#   --foreground 212 --border-foreground 212 --border double \
#   --align center --width 50 --margin "1 2" --padding "2 4" \
#     $INTRO_MESSAGE
# '''

common = """
git config --global user.name "Peter Štefka"
git config --global user.email "peter.stefka@aspecta.sk"

alias vault=openbao
alias terraform=opentofu
alias cat="bat -p"

eval "$(starship init bash)"
eval "$(direnv hook bash)"
eval "$(pyenv init - bash)"

export DELTA_FEATURES=+side-by-side # activate
git config --global core.pager delta
git config --global interactive.diffFilter 'delta --color-only'
git config --global delta.navigate true
git config --global delta.dark true  # or `delta.light true`, or omit for auto-detection
git config --global merge.conflictStyle zdiff3

# [[ $- == *i* ]] && _ble_base_run="${XDG_RUNTIME_DIR:-/tmp}/blesh-run-$(id -un)" _ble_base_cache="${XDG_CACHE_HOME:-$HOME/.cache}/blesh" source -- "$(blesh-share)/ble.sh" --attach=none
if [ ! -f ~/.blerc ]; then
  cat <<EOF > ~/.blerc
#_ble_base_run="${XDG_RUNTIME_DIR:-/tmp}/blesh-run-$(id -u)"
#_ble_base_cache="${XDG_CACHE_HOME:-$HOME/.cache}/blesh"
EOF
fi

[[ $- == *i* ]] && source -- "$(blesh-share)/ble.sh" --attach=none
# if atuin sync not initialized, login, import, sync
eval "$(atuin init bash --disable-up-arrow)"
if ! atuin login -u pstefka -p foo -k bar >/dev/null; then
  atuin login -u pstefka
  atuin import bash
  atuin sync
fi
[[ ! ${BLE_VERSION-} ]] || ble-attach

if [ ! -f ~/.bash_wd_source ]; then
  touch ~/.bash_wd_source
  warp-dir install --dotfile ~/.bash_wd_source
fi
source ~/.bash_wd_source
"""
## Shell-specific customizations such as setting aliases go here:
# bash = ...
# zsh  = ...
# fish = ...


## Services ---------------------------------------------------------
##  $ flox services start             <- Starts all services
##  $ flox services status            <- Status of running services
##  $ flox activate --start-services  <- Activates & starts all
## ------------------------------------------------------------------
[services]
# myservice.command = "python3 -m http.server"


## Include ----------------------------------------------------------
## ... environments to create a composed environment
## ------------------------------------------------------------------
[include]
# environments = [
#     { dir = "../common" }
# ]


## Build and publish your own packages ------------------------------
##  $ flox build
##  $ flox publish
## ------------------------------------------------------------------
[build]

[build.warp-dir]
description = "https://github.com/kigster/warp-dir#installation"
version = "0.0.2"
command = """
  export GEM_HOME="$out/lib/ruby/gems"

  mkdir -p $GEM_HOME
  mkdir -p $out/bin
  # Install the gem directly into the output directory
  gem install warp-dir --no-document --install-dir "$GEM_HOME" --bindir "$out/bin"
  """

## Other Environment Options -----------------------------------------
[options]
# Systems that environment is compatible with
systems = [
#   "aarch64-darwin",
#   "aarch64-linux",
#   "x86_64-darwin",
  "x86_64-linux",
]
# Uncomment to disable CUDA detection.
# cuda-detection = false

[options.activate]
mode = "run"
